deco-sites/std

commerce/types.ts
commerce/vtex/transform.ts

Adds VTEX's productReference to ProductGroup's gtin

feat: Add product reference

---

commerce/types.ts
commerce/vtex/client.ts
fresh.gen.ts
functions/vtexLegacyProductList.ts
functions/vtexSuggestions.ts

This PR add a vtexSuggestion loader that return the intelligent-search top search `/_v/api/intelligent-search/top_searches?locale=en-US`

feat: Add vtexSuggestions loader

---

commerce/vtex/client.ts
commerce/vtex/hooks/useCart.ts
commerce/vtex/types.ts

- Types to SimulationOrderForm
- Handler to call simulation API on Client

Add VTEX simulation handler on useCart

---

commerce/vtex/transform.ts
components/seo/SEOBase.tsx
components/seo/SEOPDP.tsx
components/seo/SEOPLP.tsx
fresh.gen.ts
functions/vtexLegacyRelatedProductsLoader.ts
functions/vtexProductDetailsPage.ts
import_map.json
utils/seo.ts

This PR adds canonicals extraction from breadcrumbs for plps and pdps

feat: canonicals

---

functions/vtexLegacyProductListingPage.ts

Fixes vtex legacy pagination parameter

fix: legacy pagination

---

commerce/hooks/useEvent.ts
commerce/sdk/sendAnalyticsEvent.ts
commerce/types.ts
commerce/utils/productToAnalyticsItem.ts
commerce/vtex/hooks/useCart.ts
components/Analytics.tsx
fresh.gen.ts
sections/Analytics.tsx

This PR adds:
- useEvent commerce hooks
- utilities functions to map product to analytics item
- vtex order form utility function to map order form item to analytics item

feat: Analytics Events

---

commerce/vtex/transform.ts
functions/vtexLegacyProductList.ts
functions/vtexProductList.ts

Adding categories to mapped product

---

commerce/vtex/transform.ts

Add attachments info to the legacy loaders

feat: attachments

---

import_map.json
packs/vtex/loaders/intelligentSearch/productList.ts
packs/vtex/loaders/intelligentSearch/productListingPage.ts
packs/vtex/utils/intelligentSearch.ts
schemas.gen.json

This PR enables passing hide Unavailable Items to Intelligent Search loader so users can disable on a per function

feat: hide unavailable items

---

CHANGELOG.md
commerce/vnda/hooks/useCart.ts
commerce/vnda/hooks/useVNDACart.ts
commerce/vnda/types.ts
schemas.gen.json

Related: https://github.com/deco-sites/template2/pull/1

Adding useVNDACart hook

---

functions/vtexLegacyRelatedProductsLoader.ts
import_map.json
packs/vtex/loaders/legacy/relatedProductsLoader.ts
schemas.gen.json

As title says, this PR allows passing productGroupID on Related Products

feat: Allow passing productGroupID on RelatedProducts

---

packs/vtex/utils/transform.ts

Remove productGroup from isVariantOf of product variations. This leads to a small number of repeated data

feat: remove productgroup from product variations

---

packs/vtex/hooks/useAutocomplete.ts

This PR adds a loading state to the autocomplete hook so we can add visual feedback to the users on the store. Also we use create for better logging on devTools

feat: add loading state to autocomplete hook

---

actions/vtex/newsletter/subscribe.ts
import_map.json
live.gen.ts
packs/vtex/actions/newletter/subscribe.ts
packs/vtex/utils/paths.ts
schemas.gen.json

Add new action to allow subscribing to newsletter

feat: add subscribe to newsletter section

---

components/seo/SEOPDP.tsx

Before
https://lojastorra.deco.site/live/previews/20849?_cache=1685383023942&pageId=20849&skuId=189546&path=%2Fcamiseta-masculina-sasuke-naruto-mescla-27125000010%2Fp&forceFresh=&pathTemplate=%2F%3Aslug%2Fp
After:
http://localhost:8000/live/previews/20849?_cache=1685383023942&pageId=20849&skuId=189546&path=%2Fcamiseta-masculina-sasuke-naruto-mescla-27125000010%2Fp&forceFresh=&pathTemplate=%2F%3Aslug%2Fp

Strip out HTML tags from description

---

schemas.gen.json
sections/SEOPDP.tsx
sections/SEOPLP.tsx

hotfix: use correct import paths

---

import_map.json
utils/seo.ts

fix: change rule if seo.title is null

---

components/seo/Metatags.tsx

fix: remove duplicate tags

---

components/VTEXPortalDataLayerCompatibility.tsx

Chages:
- defer scripts;
- add global variables instead parse the document;

feat: Improve performance of dataLayer compat script

---

packs/vtex/loaders/legacy/relatedProductsLoader.ts

Does not throw when product not found

fix: related products

---

import_map.json
packs/vtex/hooks/context.ts
packs/vtex/hooks/useCart.ts
packs/vtex/hooks/useUser.ts
packs/vtex/hooks/useWishlist.ts

feat: single invoke

---

packs/vtex/loaders/intelligentSearch/productListingPage.ts

More context: https://discord.com/channels/985687648595243068/1124020094419357806/1124020316423856289

Don't break when VTEX does: pages above 50

---

packs/vtex/hooks/context.ts

Returns the queue promise so legacy code can await the operation

fix: return promise

---

handlers/sitemap.ts
import_map.json
live.gen.ts
loaders/vtex/proxy.ts
packs/vtex/handlers/sitemap.ts
schemas.gen.json

This also changes the VTEX Proxy to AutoGenerate deco sitemap and use it importing from the deco-sitemap.xml

Add auto-generated sitemap

---

import_map.json
live.gen.ts
loaders/x/font.ts
packs/font/loaders/font.ts
packs/font/loaders/googleFonts.ts
packs/font/types.ts
schemas.gen.json
utils/withFontServer.ts

Add google fontapis loader and font loader.

feat: font loader

---

packs/image/engines/wasm/worker.ts

Improves image hyper parameters for faster transformations and thus better DX

feat: improve hyper parameters for faster development

---

commerce/types.ts
packs/vtex/utils/transform.ts

Adding VTEX teasers to product

---

packs/image/components/Image.tsx

Reduce possiblities to reduce load on image server

feat: remove possibilities

---

import_map.json
live.gen.ts
loaders/vtex/legacy/suggestions.ts
packs/vtex/hooks/useLegacyAutocomplete.ts

Related:
- https://github.com/deco-cx/apps/pull/8
-

Proxying Legacy Autocomplete loader

---

plugins/tailwind/mod.ts

Improves drastically the TailwindCSS performance on data plane by using the stylesheet built during the build phase

fix: Improve TailwindCSS performance on data plane
