commerce/vtex/client.ts, fresh.gen.ts, functions/occProductDetailsPage.ts, functions/shopifyProductDetailsPage.ts, functions/shopifyProductList.ts, functions/shopifyProductListingPage.ts, functions/vtexLegacyProductDetailsPage.ts, functions/vtexLegacyProductList.ts, functions/vtexLegacyProductListingPage.ts, functions/vtexProductDetailsPage.ts, functions/vtexProductList.ts, functions/vtexProductListingPage.ts
This PR adds the collection parameter to vtexLegacyProductList and vtexProductList. According to the VTEX documentation a collection and productClusterId is equivalent, so this PR adds the productClusterIds to the search requests.
Example using product clusters:
- intelligent search: as facet https://decopartnerbr.vtexcommercestable.com.br/api/io/_v/api/intelligent-search/product_search/productClusterIds/137
- Search API: as fq querystring https://decopartnerbr.vtexcommercestable.com.br/api/catalog_system/pub/products/search/jeans?fq=productClusterIds:137
This PR fixes:
- vtexLegacyProductList indexes from=0 to=count-1 because the vtex search API is indexed by 0;
- fix the configVTEX, configShopify and configOCC at respective loaders.
- Fix vtex client to use proxy path …
=> feat: add collection property to vtex and vtexLegacy ProductList loaders

commerce/occ/client.ts, commerce/shopify/client.ts, commerce/vtex/cart/useCart.ts, commerce/vtex/client.ts, commerce/vtex/withISFallback.ts, functions/vtexProductDetailsPage.ts, functions/vtexProductList.ts, functions/vtexProductListingPage.ts, functions/vtexSuggestions.ts, utils/HttpError.ts, utils/fetchAPI.ts
This PR adds a 404 fallback when IS api is not available, a.k.a, it returns a 404 status code
Also, this PR adds a new HttpError class and moves the fetchAPI from live to here.
=> feat: Prevent stores from exploding when IS api is not available.

commerce/occ/transform.ts, commerce/shopify/transform.ts, commerce/types.ts, commerce/vtex/transform.ts, commerce/yourViews/client.ts, commerce/yourViews/types.ts, commerce/yourViews/withYourViews.ts, fresh.gen.ts, functions/shopifyProductListingPage.ts, functions/vtexLegacyProductListingPage.ts, functions/vtexProductListingPage.ts, sections/configYourViews.tsx
This PR adds the YourViews client and loader functions so users may use yourViews ratings in their frontned
To use yourViews, your need to create a new loader on your website, one for each page type, and wrap it under the `withYourViews` function. For instance, to create a PDPLoader, create the file and add the following code:
```ts
import type { LoaderFunction } from "$live/types.ts";
import type { LiveState } from "$live/types.ts";
import { ConfigVTEX } from "../commerce/vtex/client.ts";
import { withYourViews } from "../commerce/yourViews/withYourViews.ts";
import productPageLoader from "./vtexProductDetailsPage.ts";
import { ConfigYourViews } from "../commerce/yourViews/client.ts";
import type { ProductDetailsPage } from "../commerce/types.ts";
/**
* @title VTEX Product Page Loader
* …
```
=> feat: add YourViews loader function

commerce/vtex/transform.ts
This PR removes the domain from the navbar loader.
Before: 
```js
{
data: [
{
href: "https://bravtexfashionstore.vtexcommercestable.com.br/masculino",
label: "Masculino",
children: []
},
{
href: "https://bravtexfashionstore.vtexcommercestable.com.br/feminino",
label: "Feminino",
children: [ [Object] ]
},
{
href: "https://bravtexfashionstore.vtexcommercestable.com.br/brindes",
label: "Brindes",
children: []
}
]
}
```
After:
```js
{
data: [
{ href: "/masculino", label: "Masculino", children: [] },
{ href: "/feminino", label: "Feminino", children: [ [Object] ] },
{ href: "/brindes", label: "Brindes", children: [] }
]
}
```
=> fix: navbar urls

components/Image.tsx, components/Picture.tsx
Solves #22 
Example:
this base image: https://ozksgdmyrqcxcwhnbepg.supabase.co/storage/v1/object/public/assets/239/5ff739e6-0e3b-4f6a-b562-aed7399a90e8
this image has naturalWidth: 4320 and naturalHeight: 1800 - aspect ratio: 0.4166666666666667 
base image output from service image without height dimension: https://ik.imagekit.io/decocx/tr:w-1440,h-/https:/ozksgdmyrqcxcwhnbepg.supabase.co/storage/v1/object/public/assets/239/5ff739e6-0e3b-4f6a-b562-aed7399a90e8
this image has naturalWidth: 1440 (from URL width) and naturalHeight: 600 -  aspect ratio: 0.4166666666666667
=> feat: Nullable height for image componente

commerce/vtex/hooks/useCart.ts, commerce/vtex/types.ts
Simulation is not tied to the current orderForm. That's why, we don't need to enqueue these requests or make sure the cart is non null. Also, simulations should be done AFTER an user interaction. For these reasons, I'm removing all unecessary signals and queues.
=> fix: Remove simulation signals from cart

commerce/vtex/types.ts, fresh.gen.ts, functions/vtexProductListingPage.ts
example:
with fuzzy auto - https://vtex-search-proxy.global.ssl.fastly.net/v2/zeedog/api/io/_v/api/intelligent-search/product_search/?page=1&count=35&query=camisa&locale=pt-br&hideUnavailableItems=true&fuzzy=auto
without fuzzy auto - https://vtex-search-proxy.global.ssl.fastly.net/v2/zeedog/api/io/_v/api/intelligent-search/product_search/?page=1&count=35&query=camisa&locale=pt-br&hideUnavailableItems=true
=> feat: fuzzy param to vtexProductListingPage

commerce/vtex/transform.ts, commerce/vtex/types.ts
Also fixes types for `productClusters` and `clusterHighlights` since they come differently:
=> Fixing category property and adding for clusters

commerce/vnda/client.ts, commerce/vtex/client.ts, commerce/yourViews/client.ts, utils/fetchAPI.ts
This PR uses the new proxy.decocache.com for vtex,vnda & yourviews clients.
This domains introduces the following architecture:
Browser -> CloudFlare -> Fastly -> Deno Deploy -> ...
To use this new proxy, add the https://proxy.decocache.com in front of your usual request, so, to use it to cache https://example.com, just
```
curl https://proxy.decocache.com/https://example.com
```
This should add the necessary stale cache to the request.
Things I'm not really sure are the cdn configuration and certificates used to setup everything
=> feat: decocache

functions/vtexLegacyRelatedProductsLoader.ts
Remove empty string of allowed values for crosselingOptions of VtexLagacyRelatedProducts. 
This allowed value causes a weird comportament that not shows any value of  `CrossSellingType` until you write a valid value of this enum and duplicate the field on CMS
example:
fixed version:
=> Remove empty string of allowed type

import_map.json, live.gen.ts, packs/vtex/loaders/legacy/productListingPage.ts, packs/vtex/utils/transform.ts, schemas.gen.json
This PR adds a new option to VTEX legacy plp loader. 
Setting filters to 'static' will add a `?fmap` param to the querystring. This param will fix the facets into the first page the user has seen. This is usefull if you want the facets not to change when navigating across the PLP and applying filters.
Not setting this param will fallback to the old behavior of changing facets. This behavior is nice since it doesn't allow the user to filter for null product lists
=> feat: add filters behavior on legacy

packs/vtex/loaders/intelligentSearch/productListingPage.ts, packs/vtex/utils/transform.ts
This PR enables URLs `/{collection}?map=productClusterIds` to work on intelligent search
=> feat: Work with legacy params on IS

tailwindv3.ts
This PR allows you to use tailwind without passing a default config. This is good if you use VSCode intellisense. 
Before
```tsx
// in dev.ts
import { tailwind } from 'deco-sites/std/tailwindv3.ts'
import config from 'tailwind.config.ts'
tailwind(config)
```
After
```
// in dev.ts
import { tailwind } from 'deco-sites/std/tailiwndv3.ts'
tailwind()  // No need to pass config. It will be auto resolved to tailwind.config.ts 🎉 
```
=> auto resolve tailwind to the default tailwind config

components/VTEXPortalDataLayerCompatibility.tsx
The GTM datalayer change the dataLayer.push, but the VTEX DataLayer compatibility should be the first of dataLayer. Knowing this, the change maintain using unshift, to add first, and push just to trigger the gtm listener
=> fix: trigger vtex compatibility event with dataLayer.push

import_map.json, packs/vtex/loaders/legacy/relatedProductsLoader.ts, packs/vtex/utils/transform.ts, schemas.gen.json
This PR fixes hideUnnavailableItems for related products. 
The issue was that the `hideUnnavailableItems` feature had to be implemented on the loader side, since VTEX API does not support this feature. This lead to us picking the an unnavailable SKU, which removed the product from the shelf. 
This PR picks an available sku instead of the first one.
=> fix: HideUnnavailableItems for related products

README.md, components/VTEXPortalDataLayerCompatibility.tsx
This PR fixes the page category of vtex compatibility layer, when page is type `otherView`.
Before:
```jsonc
{// dataLayer[0]
"pageCategory": "Department",
"pageDepartment": null,
// ....
}
{event: 'otherView'}
```
After:
```jsonc
{ // dataLayer[0]
"pageCategory": "mtv",
"pageDepartment": null,
// ....
}
{event: 'otherView'}
```
=> fix: pageCategory for vtex compatibility layer

components/seo/SEOPDP.tsx, components/seo/SEOPLP.tsx, schemas.gen.json
Nowadays the PDP and PLP do not have Favicon using the SEOPLP and SEOPDP.
https://boilerplaten1.deco.site/departamento-1
https://boilerplaten1.deco.site/bone-aberto-new-era/p?skuId=231
https://deco.cx/admin/sites/boilerplaten1/blocks/Categories?revisionId=23950d61-8080-4e5d-bcab-2fc7ea5676e5&returnUrl=%2Fadmin%2Fsites%2Fboilerplaten1%2Fpages&returnLabel=Pages&path=%252F&pathTemplate=%252F*&tab=0
https://deco.cx/admin/sites/boilerplaten1/blocks/Product%20Page?revisionId=5d2aae50-165e-42a4-b059-57d6047e8435&returnUrl=%2Fadmin%2Fsites%2Fboilerplaten1%2Fpages&returnLabel=Pages&path=%252F%253Aslug%252Fp&pathTemplate=%252F%253Aslug%252Fp&tab=0
=> feat: add favicon on PDP and PLP

packs/vtex/hooks/useAutocomplete.ts
This PR removes the fixed **"count"** param used in Autocomplete hook. This amplify the use of dynamic queries on components like a searchbar.
It alsos changes the params to more clear names, for better intellisense.
=> feat: add dynamic autocomplete search count param

packs/linxImpulse/loaders/search.ts, schemas.gen.json
As a required it's impossible to create a search page with the SearchResult block with the Loader:
=> Set query as optional on Linx Impulse loader

packs/vtex/loaders/legacy/productList.ts
This API still plays me after so long time.
=> hotfix: encode url

commerce/nuvemShop/transform.ts, commerce/shopify/transform.ts, commerce/types.ts, packs/linxImpulse/utils/transform.ts, packs/vtex/types.ts, packs/vtex/utils/transform.ts
This PR changes the brand type on the Product interface so we can use schema.org Brand interface: 
https://schema.org/Brand
This PR is a BREAKING CHANGE because it now returns a Brand object instead of a string. I, however, think that this is ok because I don't remember anyone using this field anywhere. I tested on fashion and it's ok so far
=> feat: add Brand to Product

packs/vtex/types.ts, packs/vtex/utils/transform.ts
Good morning friends,
Added to this pull request, the return of teasers for legacy loaders,
previously only intelligent-search loaders had the data filled in.
Teasers were also typed for data transformation.
Best regards.
Jonathan Lopes (Mineiro).
=> feat: added teasers to catalog loader

packs/image/components/Image.tsx
Use cover by default so developers dont need to use object-cover and have total control over dimensions
=> feat: use cover by default

packs/vtex/loaders/legacy/productListingPage.ts
It was emptying the string before
=> Fixing getTerm

packs/vtex/utils/segment.ts
When the user access some page with a UTM querystring related a promotion and they changes the page, the Segment cookie has replaced to a empty one since it do not have any querystrings on the new page.
1. Enter https://www.bite.com.br/?utm_source=futebol-bite
2. Check a product price
3. Enter on that page
4. See the bug 🐞 
Bug and Resolution video: https://www.loom.com/share/4bd0d74029c54201906c06566f251d7b?sid=efca67e7-44f2-4f2c-b3f4-9aa0682ded7e
=> Fix VTEX Segment: not replace utm by empty querystrings

components/VTEXPortalDataLayerCompatibility.tsx
VTEXPortalDataLayerCompatibility was breaking on Safari due to this method. Used a old school way to resolve this.
Screenshot do problema no Safari
=> fix: remove findLast method because of safari

utils/fetchVTEX.ts
Accents break VTEX API on utm_campaigns.
example: `&utm_campaign=Conversão`
=> Normalize utm campaign value to avoid accents.

plugins/tailwind/bundler.ts, plugins/tailwind/mod.ts
This PR Integrates TailwindCSS with Decofile. 
Currently, the TailwindCSS is cached by the revision id of the current release. If the revision changes, the stylesheet is regenerated. Future work should listen for changes on Decofile and produce only diff on the tailwind stylesheet
=> feat: Integrates TailwindCSS with Decofile

import_map.json, plugins/tailwind/deno.ts, plugins/tailwind/mod.ts
This PR makes the TailwindCSS plugin be able to resolve libraries to include components into it's building process.
And advanced feature of tailwind is being able to receive the JSX file content directly, instead of only the file path. This allow us to pass any content we wish (not only those presents on the filesystem). 
Using the aforementioned feature, I created a file resolver, where for all `.tsx` files present on the local project's filesystem, I parse the file into an AST, grab the import statements, and resolve these imports using the project's import map. Then, I do this process recursively up until all files on the import graph are visited. This is very similar to how we process the project's schema. 
Finally, I create an array with all file contents and pass it to the tailwind …
=> feat: Tailwind deps
